# Generated by Django 3.1.5 on 2021-03-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.FloatField()),
            ],
        ),
    ]
