# Generated by Django 3.1.5 on 2021-03-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(default='customer', max_length=100),
            preserve_default=False,
        ),
    ]
