# Generated by Django 3.1.5 on 2021-03-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_transaction_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
    ]
