# Generated by Django 3.1.5 on 2021-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cp',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sp',
            field=models.JSONField(null=True),
        ),
    ]
